#!/usr/bin/env bash

# start with anything provided by the system admin
if [ -f /etc/bashrc ]; then
  source /etc/bashrc
fi

# history file config
export HISTCONTROL=ignoreboth
export HISTSIZE=100000
export HISTFILESIZE=10000000
export HISTIGNORE='fg:bg:history'
shopt -s histappend

# set LINES and COLUMNS after every command
shopt -s checkwinsize

# save multi-line commands as one command
shopt -s cmdhist

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

source "$HOME/.commonrc"

use_fancy_prompt
enable_timing_display
unset_title

return 0
