#!/usr/bin/env bash

# start with anything provided by the system admin
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
  . /etc/bash_completion
fi
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# history file config
export HISTCONTROL=ignoreboth
export HISTSIZE=1000000
export HISTFILESIZE=10000000
export HISTIGNORE='fg:bg:history'
shopt -s histappend

# set LINES and COLUMNS after every command
shopt -s checkwinsize

# save multi-line commands as one command
shopt -s cmdhist

# automatically correct small typos in cd
shopt -s cdspell

# only auto-complete directory names for cd
complete -d cd

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

[ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && . /usr/share/doc/fzf/examples/key-bindings.bash
[ -f /usr/share/doc/fzf/examples/completion.bash ] && . /usr/share/doc/fzf/examples/completion.bash

. "$HOME/.commonrc"

eval "$(starship init bash)"
