#!/usr/bin/env bash

# start with anything provided by the system admin
if [ -f /etc/bashrc ]; then
  source /etc/bashrc
fi

# history file config
export HISTCONTROL=ignoreboth
export HISTSIZE=10000
export HISTFILESIZE=100000
shopt -s histappend

# set LINES and COLUMNS after every command
shopt -s checkwinsize

# save multi-line commands as one command
shopt -s cmdhist

# utf-8 everywhere
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# set default editor
export EDITOR=$(command -v vim)

# pretty display for the ninja build system
export NINJA_STATUS="%es [%u -> %r -> %f/%t] "

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# default options for less
export LESS="--quit-if-one-screen --no-init"

d="$HOME/.dircolors"
[[ -r "$d" ]] && eval "$(dircolors "$d")"

# source everything in dotfiles/sources and dotfiles/functions
DOTFILES=$(realpath ~/dotfiles)
for file in "$DOTFILES/sources/"*; do
  [[ -f $file ]] && source "$file"
done

# add dotfiles/bin to path so we can use the functions there
path_prefix $DOTFILES/bin

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# ... but modified by me
__conda_setup="$($HOME/.python/bin/conda 'shell.bash' 'hook' 2>/dev/null)"
if [ $? -eq 0 ]; then
  eval "$__conda_setup"
else
  if [ -f "$HOME/.python/etc/profile.d/conda.sh" ]; then
    source "$HOME/.python/etc/profile.d/conda.sh"
  else
    path_prefix ~/.python/bin
  fi
fi
unset __conda_setup
# <<< conda initialize <<<

# ruby environment
path_prefix ~/.rbenv/bin
if exists rbenv; then
  eval "$(rbenv init -)"
fi

# rust environment
path_prefix ~/.cargo/bin

# prefer bat to cat
if exists bat; then
  alias cat='bat'
fi

# prefer ripgrep to grep
if exists rg; then
  alias grep='rg'
fi

# turn on thefuck
if [[ ! $(exists fuck) ]]; then
  eval $(thefuck --alias)
fi

# add any local config, letting it overwrite if necessary
for file in ~/.bashrc{.,_}local; do
  [[ -f $file ]] && source "$file"
done

if exists mc; then
  complete -C $HOME/dotfiles/bin/mc mc
fi

unset_title

return 0
