#!/usr/bin/env bash

export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH"

# utf-8 everywhere
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# set truecolor on
export COLORTERM=truecolor

# set default editor
export EDITOR=$(command -v vim)

# nonlocal cd
export CDPATH=".:$HOME:$HOME/projects:$HOME/work"

# default options for less
export LESS="--quit-if-one-screen --no-init -R"

# docker options
export DOCKER_BUILDKIT=1
export DOCKER_SCAN_SUGGEST=false

d="$HOME/.dircolors"
[[ $(uname) -ne "Darwin" && -r "$d" ]] && eval "$(dircolors "$d")"

DOTFILES="$HOME/dotfiles"

. "$DOTFILES/sources/shell.sh"

# source everything in dotfiles/sources
for file in "$DOTFILES/sources/"*; do
  [[ -f $file ]] && . "$file"
done

# add dotfiles/bin to path so we can use the functions there
path_prefix "$DOTFILES/bin"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# ... but modified by me
__conda_setup="$($HOME/.python/bin/conda 'shell.bash' 'hook' 2>/dev/null)"
if [ $? -eq 0 ]; then
  eval "$__conda_setup"
else
  if [ -f "$HOME/.python/etc/profile.d/conda.sh" ]; then
    . "$HOME/.python/etc/profile.d/conda.sh"
  else
    path_prefix ~/.python/bin
  fi
fi
unset __conda_setup
# <<< conda initialize <<<

export NVM_DIR="$HOME/.nvm"
if [[ -d "$NVM_DIR" ]]; then
  . "$NVM_DIR/nvm.sh"
  . "$NVM_DIR/bash_completion"
fi

if exists yarn; then
  path_prefix "$(yarn global bin)"
fi

# rust environment
path_prefix "$HOME/.cargo/bin"

# prefer bat to cat
if exists bat; then
  alias cat='bat'
fi

# prefer ripgrep to grep
if exists rg; then
  alias grep='rg'
fi

# override some BSD utils with GNU utils from the brew findutils package
if [[ $(uname) == "Darwin" ]]; then
  path_prefix "/usr/local/opt/findutils/libexec/gnubin"
fi

# add any local config, letting it overwrite if necessary
for file in "$HOME"/.bashrc{.,_}local; do
  [[ -f $file ]] && . "$file"
done
