#!/usr/bin/env zsh

export PATH=$HOME/bin:/usr/local/bin:$PATH

autoload -Uz compinit
compinit

# Set up history search
# https://superuser.com/questions/585003/searching-through-history-with-up-and-down-arrow-in-zsh
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

source "$HOME/.commonrc"

eval "$(starship init zsh)"

export PATH="$HOME/.poetry/bin:$PATH"
